var searchData=
[
  ['objective_20recommender_20system_20by_20clicking_20the_20button_20recommend_0',['2. Now you can get recommendations from the multi-objective recommender system by clicking the button &quot;Recommend&quot;.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md3',1,'']]],
  ['objectives_20by_20metrics_20filter_20below_20the_20search_20bar_1',['3. You can tweak the objectives by metrics filter below the search bar!',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md4',1,'']]],
  ['objectives_20work_20you_20should_20click_20on_20the_20yyyyyy_20button_20just_20above_20the_20metrics_20filter_2',['If you want to know how to use the filter or find out how the different metrics/objectives work you should click on the YYYYYY button just above the metrics filter.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md5',1,'']]],
  ['of_20metrics_20filter_20and_20different_20types_20of_20explanations_20on_20why_20the_20movie_20was_20recommended_20you_20can_20change_20these_20things_20and_20some_20others_20in_20the_20app_20settings_20page_3',['6. You should try different types of metrics filter and different types of explanations on why the movie was recommended. You can change these things and some others in the APP SETTINGS page.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md8',1,'']]],
  ['of_20the_20home_20page_4',['Of the home page',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md6',1,'4. Follow the tips that are displayed in the orange card on top of the home page!'],['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md10',1,'All the required actions will be displayed in the orange card on top of the home page!']]],
  ['of_20this_20user_20study_20in_20the_20form_20page_5',['7. After you will perform all required actions you can start answering the questions of this user study in the form page.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md9',1,'']]],
  ['on_20the_20icon_20in_20the_20top_20menu_6',['You can return to this manual by clicking on the ICON in the top menu.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md1',1,'']]],
  ['on_20the_20yyyyyy_20button_20just_20above_20the_20metrics_20filter_7',['If you want to know how to use the filter or find out how the different metrics/objectives work you should click on the YYYYYY button just above the metrics filter.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md5',1,'']]],
  ['on_20this_20icon_20next_20to_20their_20names_20in_20the_20movie_20detail_20you_20can_20also_20create_20and_20manage_20blocking_20rules_20in_20the_20block_20settings_20page_8',['5. You can block some movies, actors, directors and genres by clicking on this ICON next to their names in the movie detail. You can also create and manage blocking rules in the BLOCK SETTINGS page.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md7',1,'']]],
  ['on_20top_20of_20the_20home_20page_9',['On top of the home page',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md6',1,'4. Follow the tips that are displayed in the orange card on top of the home page!'],['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md10',1,'All the required actions will be displayed in the orange card on top of the home page!']]],
  ['on_20why_20the_20movie_20was_20recommended_20you_20can_20change_20these_20things_20and_20some_20others_20in_20the_20app_20settings_20page_10',['6. You should try different types of metrics filter and different types of explanations on why the movie was recommended. You can change these things and some others in the APP SETTINGS page.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md8',1,'']]],
  ['one_20question_20to_20other_20by_20clicking_20the_20buttons_20just_20below_20the_20answer_20options_11',['8. Please answer all questions. You can move from one question to other by clicking the buttons just below the answer options.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md11',1,'']]],
  ['options_12',['8. Please answer all questions. You can move from one question to other by clicking the buttons just below the answer options.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md11',1,'']]],
  ['or_20find_20out_20how_20the_20different_20metrics_20objectives_20work_20you_20should_20click_20on_20the_20yyyyyy_20button_20just_20above_20the_20metrics_20filter_13',['If you want to know how to use the filter or find out how the different metrics/objectives work you should click on the YYYYYY button just above the metrics filter.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md5',1,'']]],
  ['orange_20card_20on_20top_20of_20the_20home_20page_14',['Orange card on top of the home page',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md6',1,'4. Follow the tips that are displayed in the orange card on top of the home page!'],['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md10',1,'All the required actions will be displayed in the orange card on top of the home page!']]],
  ['other_20by_20clicking_20the_20buttons_20just_20below_20the_20answer_20options_15',['8. Please answer all questions. You can move from one question to other by clicking the buttons just below the answer options.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md11',1,'']]],
  ['others_20in_20the_20app_20settings_20page_16',['6. You should try different types of metrics filter and different types of explanations on why the movie was recommended. You can change these things and some others in the APP SETTINGS page.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md8',1,'']]],
  ['out_20how_20the_20different_20metrics_20objectives_20work_20you_20should_20click_20on_20the_20yyyyyy_20button_20just_20above_20the_20metrics_20filter_17',['If you want to know how to use the filter or find out how the different metrics/objectives work you should click on the YYYYYY button just above the metrics filter.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md5',1,'']]]
];
