var searchData=
[
  ['want_20to_20know_20how_20to_20use_20the_20filter_20or_20find_20out_20how_20the_20different_20metrics_20objectives_20work_20you_20should_20click_20on_20the_20yyyyyy_20button_20just_20above_20the_20metrics_20filter_0',['If you want to know how to use the filter or find out how the different metrics/objectives work you should click on the YYYYYY button just above the metrics filter.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md5',1,'']]],
  ['was_20recommended_20you_20can_20change_20these_20things_20and_20some_20others_20in_20the_20app_20settings_20page_1',['6. You should try different types of metrics filter and different types of explanations on why the movie was recommended. You can change these things and some others in the APP SETTINGS page.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md8',1,'']]],
  ['webappformorecsys_2',['WebAppForMORecSys',['../namespace_web_app_for_m_o_rec_sys.html',1,'']]],
  ['webappformorecsys_3a_3aareas_3',['Areas',['../namespace_web_app_for_m_o_rec_sys_1_1_areas.html',1,'WebAppForMORecSys']]],
  ['webappformorecsys_3a_3aareas_3a_3aidentity_4',['Identity',['../namespace_web_app_for_m_o_rec_sys_1_1_areas_1_1_identity.html',1,'WebAppForMORecSys::Areas']]],
  ['webappformorecsys_3a_3aareas_3a_3aidentity_3a_3adata_5',['Data',['../namespace_web_app_for_m_o_rec_sys_1_1_areas_1_1_identity_1_1_data.html',1,'WebAppForMORecSys::Areas::Identity']]],
  ['webappformorecsys_3a_3aareas_3a_3aidentity_3a_3apages_6',['Pages',['../namespace_web_app_for_m_o_rec_sys_1_1_areas_1_1_identity_1_1_pages.html',1,'WebAppForMORecSys::Areas::Identity']]],
  ['webappformorecsys_3a_3aareas_3a_3aidentity_3a_3apages_3a_3aaccount_7',['Account',['../namespace_web_app_for_m_o_rec_sys_1_1_areas_1_1_identity_1_1_pages_1_1_account.html',1,'WebAppForMORecSys::Areas::Identity::Pages']]],
  ['webappformorecsys_3a_3aareas_3a_3aidentity_3a_3apages_3a_3aaccount_3a_3amanage_8',['Manage',['../namespace_web_app_for_m_o_rec_sys_1_1_areas_1_1_identity_1_1_pages_1_1_account_1_1_manage.html',1,'WebAppForMORecSys::Areas::Identity::Pages::Account']]],
  ['webappformorecsys_3a_3acontrollers_9',['Controllers',['../namespace_web_app_for_m_o_rec_sys_1_1_controllers.html',1,'WebAppForMORecSys']]],
  ['webappformorecsys_3a_3adata_10',['Data',['../namespace_web_app_for_m_o_rec_sys_1_1_data.html',1,'WebAppForMORecSys']]],
  ['webappformorecsys_3a_3adata_3a_3acache_11',['Cache',['../namespace_web_app_for_m_o_rec_sys_1_1_data_1_1_cache.html',1,'WebAppForMORecSys::Data']]],
  ['webappformorecsys_3a_3ahelpers_12',['Helpers',['../namespace_web_app_for_m_o_rec_sys_1_1_helpers.html',1,'WebAppForMORecSys']]],
  ['webappformorecsys_3a_3ahelpers_3a_3ajsonpropertieshandlers_13',['JSONPropertiesHandlers',['../namespace_web_app_for_m_o_rec_sys_1_1_helpers_1_1_j_s_o_n_properties_handlers.html',1,'WebAppForMORecSys::Helpers']]],
  ['webappformorecsys_3a_3ahelpers_3a_3amovielensloaders_14',['MovielensLoaders',['../namespace_web_app_for_m_o_rec_sys_1_1_helpers_1_1_movielens_loaders.html',1,'WebAppForMORecSys::Helpers']]],
  ['webappformorecsys_3a_3aloggers_15',['Loggers',['../namespace_web_app_for_m_o_rec_sys_1_1_loggers.html',1,'WebAppForMORecSys']]],
  ['webappformorecsys_3a_3amigrations_16',['Migrations',['../namespace_web_app_for_m_o_rec_sys_1_1_migrations.html',1,'WebAppForMORecSys']]],
  ['webappformorecsys_3a_3amodels_17',['Models',['../namespace_web_app_for_m_o_rec_sys_1_1_models.html',1,'WebAppForMORecSys']]],
  ['webappformorecsys_3a_3amodels_3a_3aitemdomainextension_18',['ItemDomainExtension',['../namespace_web_app_for_m_o_rec_sys_1_1_models_1_1_item_domain_extension.html',1,'WebAppForMORecSys::Models']]],
  ['webappformorecsys_3a_3amodels_3a_3aitemdomainextension_3a_3amovie_19',['Movie',['../namespace_web_app_for_m_o_rec_sys_1_1_models_1_1_item_domain_extension_1_1_movie.html',1,'WebAppForMORecSys::Models::ItemDomainExtension']]],
  ['webappformorecsys_3a_3amodels_3a_3aviewmodels_20',['ViewModels',['../namespace_web_app_for_m_o_rec_sys_1_1_models_1_1_view_models.html',1,'WebAppForMORecSys::Models']]],
  ['webappformorecsys_3a_3arequesthandlers_21',['RequestHandlers',['../namespace_web_app_for_m_o_rec_sys_1_1_request_handlers.html',1,'WebAppForMORecSys']]],
  ['webappformorecsys_3a_3asettings_22',['Settings',['../namespace_web_app_for_m_o_rec_sys_1_1_settings.html',1,'WebAppForMORecSys']]],
  ['whitelistitemids_23',['WhiteListItemIDs',['../class_web_app_for_m_o_rec_sys_1_1_request_handlers_1_1_recommender_query.html#a431221115fbfec030ad848c948009582',1,'WebAppForMORecSys::RequestHandlers::RecommenderQuery']]],
  ['why_20not_20use_20pure_20css_24',['Why not use pure CSS?',['../md__web_app_for_m_o_rec_sys_2wwwroot_2lib_2popperjs_2core_2_r_e_a_d_m_e.html#autotoc_md15',1,'']]],
  ['why_20popper_25',['Why Popper?',['../md__web_app_for_m_o_rec_sys_2wwwroot_2lib_2popperjs_2core_2_r_e_a_d_m_e.html#autotoc_md16',1,'']]],
  ['why_20the_20movie_20was_20recommended_20you_20can_20change_20these_20things_20and_20some_20others_20in_20the_20app_20settings_20page_26',['6. You should try different types of metrics filter and different types of explanations on why the movie was recommended. You can change these things and some others in the APP SETTINGS page.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md8',1,'']]],
  ['will_20be_20displayed_20in_20the_20orange_20card_20on_20top_20of_20the_20home_20page_27',['All the required actions will be displayed in the orange card on top of the home page!',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md10',1,'']]],
  ['will_20perform_20all_20required_20actions_20you_20can_20start_20answering_20the_20questions_20of_20this_20user_20study_20in_20the_20form_20page_28',['7. After you will perform all required actions you can start answering the questions of this user study in the form page.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md9',1,'']]],
  ['work_20properly_29',['1. Go to the home page and rate positively atleast 3 movies you like so the recommender system can work properly.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md2',1,'']]],
  ['work_20you_20should_20click_20on_20the_20yyyyyy_20button_20just_20above_20the_20metrics_20filter_30',['If you want to know how to use the filter or find out how the different metrics/objectives work you should click on the YYYYYY button just above the metrics filter.',['../md__web_app_for_m_o_rec_sys_2_help.html#autotoc_md5',1,'']]]
];
